### ISSUE TITLE
NameError: name 'alchemyjsonschema' is not defined

### ISSUE THREAD

**Issue by twodayslate** [lockie/tornado_jsonapi#1]
```
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    main()
  File "main.py", line 42, in main
    Post, Session))
  File "/Users/zrgorak/.pyenv/versions/3.7.3/lib/python3.7/site-packages/tornado_jsonapi/resource.py", line 112, in __init__
    factory = alchemyjsonschema.SchemaFactory(
NameError: name 'alchemyjsonschema' is not defined
```

Running the [sqla.py](https://github.com/lockie/tornado_jsonapi/blob/master/examples/sqla.py) demo

If I manually `pip install alchemyjsonschema` I then get

```
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    main()
  File "main.py", line 42, in main
    Post, Session))
  File "/Users/zrgorak/.pyenv/versions/3.7.3/lib/python3.7/site-packages/tornado_jsonapi/resource.py", line 113, in __init__
    alchemyjsonschema.AlsoChildrenWalker)
AttributeError: module 'alchemyjsonschema' has no attribute 'AlsoChildrenWalker'
```
Needs to be renamed to `StructuralWalker`. See [issue #11](https://github.com/podhmo/alchemyjsonschema/issues/11) for name change reference.

**Comment by lockie** [comment]
You'll need to install the package with the corresponding extra:
```sh
pip install tornado_jsonapi[sqlalchemy]
```
it will pull the required versions of the packages.
